// src/app/api/translate/route.ts
//
// Server-side translation endpoint. Receives a blockId + target locale,
// finds the source OLX file, translates via LLM, saves to LOFS,
// re-syncs content, and returns the updated idMap for affected blocks.
//
// File naming convention:
//   demos/algebra101lesson.olx → demos/algebra101lesson/ar-Arab-SA.olx
//

import { NextResponse } from 'next/server';
import path from 'path';
import { FileStorageProvider } from '@/lib/lofs/providers/file';
import { syncContentFromStorage, getSourceFile, getBlocksForFiles, getBlockVariant, getOriginalVariant } from '@/lib/content/syncContentFromStorage';
import { callLLM } from '@/lib/llm/serverCall';
import { getProvider } from '@/lib/llm/provider';
import { getLanguageLabel } from '@/lib/i18n/languages';
import { hashContent } from '@/lib/util';
import yaml from 'js-yaml';

const contentDir = process.env.OLX_CONTENT_DIR || './content';
const provider = new FileStorageProvider(contentDir);

// Server-side dedup: concurrent requests for same file+locale await the same promise
const inFlightTranslations = new Map<string, Promise<any>>();

type TranslationResult = { ok: boolean; idMap?: any; error?: string };

// =============================================================================
// String Helpers
// =============================================================================

/** Strip markdown code fences that LLMs sometimes add.

    We should confirm this is needed later. It is likely just a
    property of a dev LLM.
 */
function stripCodeFences(text: string): string {
  let result = text.trim();
  if (result.startsWith('```')) {
    const firstNewline = result.indexOf('\n');
    if (firstNewline !== -1) {
      result = result.slice(firstNewline + 1);
    }
    if (result.endsWith('```')) {
      result = result.slice(0, -3).trimEnd();
    }
  }
  return result;
}

/** Extract leading XML comments and body from content.
 *  Returns comment texts (for metadata extraction) and the body (root element onward).
 *  Comments inside the document (child metadata, etc.) are preserved in body. */
function extractLeadingComments(content: string): { comments: string[]; body: string } {
  const comments: string[] = [];
  let s = content;
  while (true) {
    s = s.trimStart();
    if (!s.startsWith('<!--')) break;
    const endIdx = s.indexOf('-->');
    if (endIdx === -1) break;
    comments.push(s.slice(4, endIdx).trim());
    s = s.slice(endIdx + 3);
  }
  return { comments, body: s.trimStart() };
}

/** Try to parse YAML frontmatter from extracted comment texts.
 *  Looks for a comment with --- delimiters and parses the YAML inside. */
function parseMetadataFromComments(comments: string[]): Record<string, any> {
  for (const text of comments) {
    const match = text.match(/^---\s*\n([\s\S]*?)\n\s*---\s*$/);
    if (!match) continue;
    try {
      return (yaml.load(match[1]) as Record<string, any>) || {};
    } catch {
      continue;
    }
  }
  return {};
}

/** Build YAML frontmatter comment from a metadata object. */
function buildFrontmatter(metadata: Record<string, any>): string {
  const body = yaml.dump(metadata, { lineWidth: -1 }).trimEnd();
  return `<!--\n---\n${body}\n---\n-->`;
}

// =============================================================================
// Path Helpers
// =============================================================================

// demos/algebra101lesson.olx → demos/algebra101lesson/ar-Arab-SA.olx
function computeTranslationPath(sourceRelPath: string, targetLocale: string): string {
  const ext = path.extname(sourceRelPath);
  const base = sourceRelPath.slice(0, -ext.length);
  return `${base}/${targetLocale}${ext}`;
}

/** Convert a file:// URI to a provider-relative path. */
function uriToRelPath(fileUri: string): string {
  const absPath = fileUri.startsWith('file://') ? fileUri.slice(7) : fileUri;
  return path.relative(path.resolve(contentDir), absPath);
}

/** Convert a provider-relative path to a file:// URI. */
function relPathToUri(relPath: string): string {
  return `file://${path.resolve(contentDir, relPath)}`;
}

// =============================================================================
// Translation Pipeline
// =============================================================================

/** If the source is a translation, follow source_file back to the original.
 *  Always translate from human-authored source to avoid quality degradation. */
function resolveOriginalFileUri(sourceFileUri: string, blockId: string, sourceLocale: string): string {
  const sourceVariant = getBlockVariant(blockId, sourceLocale);
  if (!sourceVariant?.autogenerated || !sourceVariant?.source_file) {
    return sourceFileUri;
  }
  const originalFileName = sourceVariant.source_file as string;
  const sourceRelPath = uriToRelPath(sourceFileUri);
  const originalRelPath = path.join(path.dirname(path.dirname(sourceRelPath)), originalFileName);
  return relPathToUri(originalRelPath);
}

/** Check if a translation already exists. If so, re-sync and return its blocks. */
async function checkExistingTranslation(
  targetRelPath: string,
  sourceFileUri: string
): Promise<TranslationResult | null> {
  try {
    await provider.read(targetRelPath);
  } catch {
    return null; // Doesn't exist — proceed with translation
  }
  await syncContentFromStorage();
  return { ok: true, idMap: getBlocksForFiles(sourceFileUri, relPathToUri(targetRelPath)) };
}

/** Build the LLM prompt for OLX translation. */
function buildTranslationPrompt(
  sourceLocale: string,
  targetLocale: string
): { role: string; content: string }[] {
  const systemPrompt = `You are a translator for educational content in OLX (XML) format.

Rules for XML content:
- Translate ALL human-readable text (text between tags, attribute values like "title", "label", "placeholder", "description")
- PRESERVE all XML tags, tag names, id attributes, and structural attributes unchanged
- Do NOT translate: id values, ref values, tag names, CSS classes, LaTeX formulas, code blocks
- Maintain the exact same XML structure and nesting
- For mathematical content, preserve formulas but translate surrounding text
- Use natural, culturally appropriate phrasing

Rules for YAML metadata comments (<!-- --- ... --- -->):
- Translate "description" and "title" values
- Do NOT translate "category" — keep it unchanged
- Set "lang" to "${targetLocale}"
- Keep all other fields unchanged
- Preserve the exact <!-- --- ... --- --> comment format

Output ONLY the translated content — no explanations, no markdown fencing, no commentary.`;

  return [{ role: 'system', content: systemPrompt }];
}

/** Call the LLM to translate OLX content. */
async function translateWithLLM(
  sourceContent: string,
  sourceLocale: string,
  targetLocale: string
): Promise<string> {
  const sourceLanguageName = getLanguageLabel(sourceLocale, 'en', 'name');
  const targetLanguageName = getLanguageLabel(targetLocale, 'en', 'name');
  const messages = [
    ...buildTranslationPrompt(sourceLocale, targetLocale),
    { role: 'user', content: `Translate the following OLX content from ${sourceLanguageName} to ${targetLanguageName}:\n\n${sourceContent}` },
  ];
  const raw = await callLLM(messages);
  const cleaned = stripCodeFences(raw);
  if (!cleaned.trim()) {
    throw new Error('LLM returned empty translation');
  }
  return cleaned;
}

/** Build the translated file: merge LLM-translated metadata with provenance fields. */
async function buildTranslatedFile(
  llmOutput: string,
  sourceContent: string,
  effectiveRelPath: string,
  targetLocale: string,
  blockId: string
): Promise<string> {
  const { comments, body } = extractLeadingComments(llmOutput);
  const llmMeta = parseMetadataFromComments(comments);
  const originalVariant = getOriginalVariant(blockId);

  const translatedMeta: Record<string, any> = {
    ...llmMeta,
    ...(originalVariant?.category && { category: originalVariant.category }),
    lang: targetLocale,
    autogenerated: true,
    source_file: path.basename(effectiveRelPath),
    source_version: await hashContent(sourceContent),
  };

  return `${buildFrontmatter(translatedMeta)}\n${body}`;
}

/** Write a translated file to storage, creating parent directories as needed. */
async function writeTranslatedFile(targetRelPath: string, fileContent: string): Promise<void> {
  const fs = await import('fs/promises');
  const fullTargetPath = path.resolve(contentDir, targetRelPath);
  await fs.mkdir(path.dirname(fullTargetPath), { recursive: true });
  await provider.write(targetRelPath, fileContent);
}

// =============================================================================
// Main Entry Point
// =============================================================================

async function doTranslation(
  blockId: string,
  sourceFileUri: string,
  targetLocale: string,
  sourceLocale: string
): Promise<TranslationResult> {
  // Resolve to the human-authored original (skip intermediate translations)
  const effectiveFileUri = resolveOriginalFileUri(sourceFileUri, blockId, sourceLocale);
  const effectiveRelPath = uriToRelPath(effectiveFileUri);

  // Read source file content
  let sourceContent: string;
  try {
    sourceContent = (await provider.read(effectiveRelPath)).content;
  } catch (err: any) {
    return { ok: false, error: `Failed to read source file "${effectiveRelPath}": ${err.message}` };
  }

  // Return early if translation already exists
  const targetRelPath = computeTranslationPath(effectiveRelPath, targetLocale);
  const existing = await checkExistingTranslation(targetRelPath, sourceFileUri);
  if (existing) return existing;

  // Translate via LLM
  let llmOutput: string;
  try {
    llmOutput = await translateWithLLM(sourceContent, sourceLocale, targetLocale);
  } catch (err: any) {
    return { ok: false, error: `LLM translation failed: ${err.message}` };
  }

  // Build and write translated file
  const fileContent = await buildTranslatedFile(llmOutput, sourceContent, effectiveRelPath, targetLocale, blockId);
  try {
    await writeTranslatedFile(targetRelPath, fileContent);
  } catch (err: any) {
    return { ok: false, error: `Failed to write translation: ${err.message}` };
  }

  // Re-sync and return blocks from both source and translated files
  await syncContentFromStorage();
  return { ok: true, idMap: getBlocksForFiles(sourceFileUri, relPathToUri(targetRelPath)) };
}

// =============================================================================
// Route Handler
// =============================================================================

export async function POST(request: Request) {
  try {
    const { blockId, targetLocale, sourceLocale } = await request.json();

    if (!blockId || !targetLocale || !sourceLocale) {
      return NextResponse.json(
        { ok: false, error: 'Missing required fields: blockId, targetLocale, sourceLocale' },
        { status: 400 }
      );
    }

    // Validate locale format (BCP 47: alphanumeric segments separated by hyphens)
    //
    // Paths should be validated by the storage provider before write, but this is
    // part of defense-in-depth. It will need to be expanded when variants expand
    // beyond locale.
    const bcp47Re = /^[a-zA-Z0-9]+(-[a-zA-Z0-9]+)*$/;
    if (!bcp47Re.test(targetLocale) || !bcp47Re.test(sourceLocale)) {
      return NextResponse.json(
        { ok: false, error: 'Invalid locale format' },
        { status: 400 }
      );
    }

    // Stub mode: no real translation available
    if (getProvider().provider === 'stub') {
      return NextResponse.json(
        { ok: false, error: 'LLM is in stub mode — no real translation available' }
      );
    }

    // Look up source file from blockId + sourceLocale
    const sourceFileUri = getSourceFile(blockId, sourceLocale);
    if (!sourceFileUri) {
      return NextResponse.json(
        { ok: false, error: `Block "${blockId}" not found for locale "${sourceLocale}"` },
        { status: 404 }
      );
    }

    // Dedup: if same file+locale is already in flight, await that instead
    const dedupeKey = `${sourceFileUri}::${targetLocale}`;
    if (inFlightTranslations.has(dedupeKey)) {
      const result = await inFlightTranslations.get(dedupeKey);
      return NextResponse.json(result);
    }

    const promise = doTranslation(blockId, sourceFileUri, targetLocale, sourceLocale);
    inFlightTranslations.set(dedupeKey, promise);

    try {
      const result = await promise;
      if (!result.ok) {
        return NextResponse.json(result, { status: 500 });
      }
      return NextResponse.json(result);
    } finally {
      inFlightTranslations.delete(dedupeKey);
    }
  } catch (error: any) {
    console.error('[/api/translate] Error:', error);
    return NextResponse.json(
      { ok: false, error: error.message || 'Unknown error' },
      { status: 500 }
    );
  }
}
